services:
  mqtt:
    container_name: mqtt
    hostname: mqtt
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto:/mosquitto
    restart: always

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    container_name: mqtt-dashboard
    ports:
      - 4000:4000
    restart: unless-stopped

